import 'package:kmdha/constant/img_constants.dart';
import 'type_shop.dart';

final List<TypeShop> allShops = [
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Starbucks Coffee',
    description: 'Cafe • Beverages',
    rating: 3.9,
    deliveryTime: 23,
    distance: 4.0,
    discount: 'Flat ₹125 OFF',
    category: 'Cafe',
    price: 350,
  ),
  TypeShop(
    imageUrl: shopImageNetwork2,
    name: 'Costa Coffee',
    description: 'Cafe • Snacks',
    rating: 4.2,
    deliveryTime: 15,
    distance: 2.5,
    discount: 'Flat ₹100 OFF',
    category: 'Cafe',
    price: 300,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Cafe Coffee Day',
    description: 'Cafe • Desserts',
    rating: 4.0,
    deliveryTime: 20,
    distance: 3.0,
    discount: 'Flat ₹150 OFF',
    category: 'Cafe',
    price: 250,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Barista',
    description: 'Cafe • Fast Food',
    rating: 3.8,
    deliveryTime: 18,
    distance: 1.5,
    discount: 'Flat ₹120 OFF',
    category: 'Cafe',
    price: 320,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Blue Tokai Coffee Roasters',
    description: 'Cafe • Organic',
    rating: 4.5,
    deliveryTime: 25,
    distance: 5.0,
    discount: 'Flat ₹200 OFF',
    category: 'Cafe',
    price: 400,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Third Wave Coffee Roasters',
    description: 'Cafe • Specialty Coffee',
    rating: 4.3,
    deliveryTime: 22,
    distance: 3.5,
    discount: 'Flat ₹175 OFF',
    category: 'Cafe',
    price: 380,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'The Coffee Bean & Tea Leaf',
    description: 'Cafe • Gourmet',
    rating: 4.1,
    deliveryTime: 17,
    distance: 2.8,
    discount: 'Flat ₹110 OFF',
    category: 'Cafe',
    price: 310,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Dunkin\' Donuts',
    description: 'Cafe • Donuts',
    rating: 3.7,
    deliveryTime: 19,
    distance: 2.0,
    discount: 'Flat ₹90 OFF',
    category: 'Cafe',
    price: 280,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'Gloria Jean\'s Coffees',
    description: 'Cafe • Bakery',
    rating: 3.9,
    deliveryTime: 21,
    distance: 4.2,
    discount: 'Flat ₹130 OFF',
    category: 'Cafe',
    price: 340,
  ),
  TypeShop(
    imageUrl: shopImageNetwork1,
    name: 'McCafe',
    description: 'Cafe • Fast Food',
    rating: 4.0,
    deliveryTime: 24,
    distance: 5.5,
    discount: 'Flat ₹140 OFF',
    category: 'Cafe',
    price: 360,
  ),
];
